/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package com.sitatec.controller;

import com.sitatec.controller.exceptions.NonexistentEntityException;
import com.sitatec.controller.exceptions.PreexistingEntityException;
import com.sitatec.model.PhoneCall;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.persistence.EntityNotFoundException;
import javax.persistence.criteria.CriteriaQuery;
import javax.persistence.criteria.Root;

/**
 *
 * @author Julian
 */
public class PhoneCallJpaController {

    public PhoneCallJpaController() {
        emf = Persistence.createEntityManagerFactory("Sitatec_ProjectPU");
    }
    private EntityManagerFactory emf = null;

    public EntityManager getEntityManager() {
        return emf.createEntityManager();
    }

    public void bussinessLogicValidations(PhoneCall phoneCall) throws PreexistingEntityException, Exception {
        SimpleDateFormat simpleDateFormat = new SimpleDateFormat("yyyy/MM/ddH:mm:ss");
        try {
            Date date = simpleDateFormat.parse(phoneCall.getStartTime());
        } catch (Exception e) {
            throw new Exception("La hora inicial de la llamada está en un formato incorrecto.");
        }

        try {
            Date date = simpleDateFormat.parse(phoneCall.getEndTime());
        } catch (Exception e) {
            throw new Exception("La hora final de la llamada está en un formato incorrecto.");
        }

        try {
            Date date1 = simpleDateFormat.parse(phoneCall.getStartTime());
            Date date2 = simpleDateFormat.parse(phoneCall.getEndTime());
            long diff = date2.getTime() - date1.getTime();
            
            if (diff < 0) {
                throw new Exception("La hora final de la llamada no puede ser menor que la hora inicial de la llamada.");
            }
        } catch (Exception e) {
            throw new Exception("La hora final de la llamada no puede ser menor que la hora inicial de la llamada.");
        }
    }

    public void create(PhoneCall phoneCall) throws PreexistingEntityException, Exception {
        EntityManager em = null;
        phoneCall.setId(getAutogeneratedId());

        try {
            em = getEntityManager();
            em.getTransaction().begin();
            em.persist(phoneCall);
            em.getTransaction().commit();
        } catch (Exception ex) {
            if (findPhoneCall(phoneCall.getId()) != null) {
                throw new PreexistingEntityException("PhoneCall " + phoneCall + " already exists.", ex);
            }
            throw ex;
        } finally {
            if (em != null) {
                em.close();
            }
        }
    }

    public int getAutogeneratedId() {
        return this.getPhoneCallCount() + 1;
    }

    public void edit(PhoneCall phoneCall) throws NonexistentEntityException, Exception {
        EntityManager em = null;
        bussinessLogicValidations(phoneCall);
        
        try {
            em = getEntityManager();
            em.getTransaction().begin();
            phoneCall = em.merge(phoneCall);
            em.getTransaction().commit();
        } catch (Exception ex) {
            String msg = ex.getLocalizedMessage();
            if (msg == null || msg.length() == 0) {
                Integer id = phoneCall.getId();
                if (findPhoneCall(id) == null) {
                    throw new NonexistentEntityException("The phoneCall with id " + id + " no longer exists.");
                }
            }
            throw ex;
        } finally {
            if (em != null) {
                em.close();
            }
        }
    }

    public void destroy(Integer id) throws NonexistentEntityException {
        EntityManager em = null;
        try {
            em = getEntityManager();
            em.getTransaction().begin();
            PhoneCall phoneCall;
            try {
                phoneCall = em.getReference(PhoneCall.class, id);
                phoneCall.getId();
            } catch (EntityNotFoundException enfe) {
                throw new NonexistentEntityException("The phoneCall with id " + id + " no longer exists.", enfe);
            }
            em.remove(phoneCall);
            em.getTransaction().commit();
        } finally {
            if (em != null) {
                em.close();
            }
        }
    }

    public List<PhoneCall> findPhoneCallEntities() {
        return findPhoneCallEntities(true, -1, -1);
    }

    public List<PhoneCall> findPhoneCallsByOriginNumber(List<PhoneCall> listPhoneCalls, String originNumber) {
        List<PhoneCall> phoneCalls = new ArrayList<PhoneCall>();
        for(PhoneCall phoneCall: listPhoneCalls) {
            if(phoneCall.getOriginNumber().equals(originNumber)) {
                phoneCalls.add(phoneCall);
            }
        }
        return phoneCalls;
    }

    public List<PhoneCall> findPhoneCallsByDestinationNumber(List<PhoneCall> listPhoneCalls, String destinationNumber) {
        List<PhoneCall> phoneCalls = new ArrayList<PhoneCall>();
        for(PhoneCall phoneCall: listPhoneCalls) {
            if(phoneCall.getDestinationNumber().equals(destinationNumber)) {
                phoneCalls.add(phoneCall);
            }
        }
        return phoneCalls;
    }

    public List<PhoneCall> findPhoneCallsByDuration(List<PhoneCall> listPhoneCalls, long duration) {
        List<PhoneCall> phoneCalls = new ArrayList<PhoneCall>();
        for(PhoneCall phoneCall: listPhoneCalls) {
            if(phoneCall.getDuration() == duration) {
                phoneCalls.add(phoneCall);
            }
        }
        return phoneCalls;
    }

    public List<PhoneCall> findPhoneCallsByCost(List<PhoneCall> listPhoneCalls, long cost) {
        List<PhoneCall> phoneCalls = new ArrayList<PhoneCall>();
        for(PhoneCall phoneCall: listPhoneCalls) {
            if(phoneCall.getCost() == cost) {
                phoneCalls.add(phoneCall);
            }
        }
        return phoneCalls;
    }

    public List<PhoneCall> findPhoneCallEntities(int maxResults, int firstResult) {
        return findPhoneCallEntities(false, maxResults, firstResult);
    }

    private List<PhoneCall> findPhoneCallEntities(boolean all, int maxResults, int firstResult) {
        EntityManager em = getEntityManager();
        try {
            CriteriaQuery cq = em.getCriteriaBuilder().createQuery();
            cq.select(cq.from(PhoneCall.class));
            Query q = em.createQuery(cq);
            if (!all) {
                q.setMaxResults(maxResults);
                q.setFirstResult(firstResult);
            }
            return q.getResultList();
        } finally {
            em.close();
        }
    }

    public PhoneCall findPhoneCall(Integer id) {
        EntityManager em = getEntityManager();
        try {
            return em.find(PhoneCall.class, id);
        } finally {
            em.close();
        }
    }

    public int getPhoneCallCount() {
        EntityManager em = getEntityManager();
        try {
            CriteriaQuery cq = em.getCriteriaBuilder().createQuery();
            Root<PhoneCall> rt = cq.from(PhoneCall.class);
            cq.select(em.getCriteriaBuilder().count(rt));
            Query q = em.createQuery(cq);
            return ((Long) q.getSingleResult()).intValue();
        } finally {
            em.close();
        }
    }

}
